Repository TheRealGD/therealgd, pull requests merged in 2018-03, with the labels that each got.

#54 docs: add new dev/test/prod db instructions
  docs/database-setup.md
Labels: AWS, devops

#61 Moderation post list 27
  config/app_routes/forum.yaml
  src/Controller/ForumController.php
  src/Entity/Submission.php
  src/Form/Model/SubmissionData.php
  src/Form/SubmissionType.php
  src/Migrations/Version20180326202804.php
  src/Repository/ForumRepository.php
  src/Repository/SubmissionRepository.php
  templates/forum/base.html.twig
  templates/forum/forum.html.twig
  templates/submission/_form.html.twig
  translations/messages.en.yml
Labels: UI

#72 Submission: urlencode() url before form submit in JS Fixes #37
  assets/js/main.js
  assets/js/submit.js
  templates/submission/_form.html.twig
Labels: UI, bug, enhancement

#106 CommentController: redirect to submission on comment(). Closes #105
  src/Controller/CommentController.php
Labels: UI, enhancement

#85 hiding modforum on categories page
  config/app_routes/submission.yaml
  src/Controller/ForumController.php
  src/Controller/FrontController.php
  src/Controller/SubmissionController.php
  src/Form/Model/SubmissionData.php
  src/Form/SubmissionType.php
  src/Repository/ForumCategoryRepository.php
  src/Repository/ForumRepository.php
  src/Repository/SubmissionRepository.php
  src/Utils/PermissionsChecker.php
  templates/forum/base.html.twig
  templates/submission/_form.html.twig
  templates/submission/mod_base.html.twig
  templates/submission/mod_submission.html.twig
  translations/messages.en.yml
Labels: UI, bug
