Repository TheRealGD/therealgd, pull requests merged in 2018-04, with the labels that each got.

#157 Clean up .gitignore a bit
  .gitignore
Labels: devops, tiny

#152 Re-write Docker for Prod-like dev on AWS w/ SSM and Local!
  .dockerignore
  .env.erb
  .gitignore
  Dockerfile
  Dockerfile-prod
  composer.json
  dev-aws.sh
  dev-local.sh
  docker-compose.yaml
  docker-compose.yaml.aws.erb
  docker/nginx/.gitignore
  docker/nginx/Dockerfile
  docker/nginx/config/crontab
  docker/nginx/config/nginx.conf.erb
  docker/nginx/config/snippets/options-ssl-nginx.conf
  docker/nginx/config/snippets/security.conf
  docker/nginx/gundeals.local
  docker/nginx/nginx.conf
  docker/nginx/scripts/entrypoint.sh
  docker/nginx/scripts/updatecerts.sh
  docker/php/Dockerfile
  docker/php/php-overrides.ini
  docs/ACKNOWLEDGEMENTS.md
  docs/CHANGELOG.md
  docs/README-old.md
  package-lock.json
Labels: ANAL BLEEDING, AWS, Continuous Delivery, Continuous Integration, ITS HAPPENING IT"S HAPPUNDF#*UIN, devops

#158 Issue 86 - Submission and comment violation reporting
  assets/js/main.js
  assets/js/report.js
  config/app_routes/comment.yaml
  config/app_routes/submission.yaml
  src/Controller/CommentController.php
  src/Controller/SubmissionController.php
  src/Entity/Comment.php
  src/Entity/Submission.php
  src/Migrations/Version20180403185827.php
  src/Migrations/Version20180405030642.php
  src/Security/Exception/AccountDisabledException.php
  src/Security/UserChecker.php
  src/Utils/ReportHelper.php
  templates/comment/_macros.html.twig
  templates/submission/_macros.html.twig
  translations/messages.en.yml
Labels: AWAITING CLOSURE

#184 Enable APCu and use it in some queries
  Dockerfile-prod
  config/packages/doctrine.yaml
  src/Repository/ForumConfigurationRepository.php
  src/Repository/ForumRepository.php
  src/Repository/SubmissionRepository.php
  src/Repository/UserRepository.php
Labels: DB, Simple PHP, enhancement

#195 Add scripts/addswap.sh
  scripts/addswap.sh
Labels: IT SHALL BE DONE, devops, tiny

#205 Remove confusing deal(s)/categories from messages - Part 1 of #198
  translations/messages.en.yml
Labels: Pure Front-End (HTML/JS/CSS Only), tiny

#208 Fix announcements - Fixes #180
  CONTRIBUTING.md
  config/packages/dev/monolog.yaml
  db-local.sh
  docker-compose.yaml
  src/Controller/FrontPageConfigurationController.php
  src/Migrations/Version20180425200406.php
  src/Repository/ForumRepository.php
  src/Repository/SubmissionRepository.php
  src/Repository/UserRepository.php
Labels: enhancement
